name: Build

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cross-compiler
        run: sudo apt install gcc-mingw-w64-x86-64

      - name: Setup V
        uses: vlang/setup-v@v1.4

      - name: Build the project
        run: v run build.vsh
