name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install cross-compiler
        run: sudo apt install gcc-mingw-w64-x86-64

      - name: Install V
        run: |
          git clone --depth=1 https://github.com/vlang/v
          cd v
          make
          sudo ./v symlink
          v up

      - name: Build the project
        run: v run build.vsh

      - name: Generate changelog
        uses: orhun/git-cliff-action@v3
        with:
          args: --verbose --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          files: |
            rr-dl.exe
            rr-dl_linux_amd64
            CHANGELOG.md
